// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: plasmod/v1/plasmod.proto

package plasmodv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlasmodAPIService_Health_FullMethodName        = "/plasmod.v1.PlasmodAPIService/Health"
	PlasmodAPIService_IngestEvent_FullMethodName   = "/plasmod.v1.PlasmodAPIService/IngestEvent"
	PlasmodAPIService_IngestVectors_FullMethodName = "/plasmod.v1.PlasmodAPIService/IngestVectors"
	PlasmodAPIService_Query_FullMethodName         = "/plasmod.v1.PlasmodAPIService/Query"
	PlasmodAPIService_QueryBatch_FullMethodName    = "/plasmod.v1.PlasmodAPIService/QueryBatch"
)

// PlasmodAPIServiceClient is the client API for PlasmodAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlasmodAPIService exposes the same warm-segment ingest/query semantics as the HTTP JSON API.
// Default listen: PLASMOD_GRPC_ADDR (see app/ports.go). HTTP remains on :8080 / :19530.
type PlasmodAPIServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error)
	IngestVectors(ctx context.Context, in *IngestVectorsRequest, opts ...grpc.CallOption) (*IngestVectorsResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	QueryBatch(ctx context.Context, in *QueryBatchRequest, opts ...grpc.CallOption) (*QueryBatchResponse, error)
}

type plasmodAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlasmodAPIServiceClient(cc grpc.ClientConnInterface) PlasmodAPIServiceClient {
	return &plasmodAPIServiceClient{cc}
}

func (c *plasmodAPIServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PlasmodAPIService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plasmodAPIServiceClient) IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestEventResponse)
	err := c.cc.Invoke(ctx, PlasmodAPIService_IngestEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plasmodAPIServiceClient) IngestVectors(ctx context.Context, in *IngestVectorsRequest, opts ...grpc.CallOption) (*IngestVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestVectorsResponse)
	err := c.cc.Invoke(ctx, PlasmodAPIService_IngestVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plasmodAPIServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, PlasmodAPIService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plasmodAPIServiceClient) QueryBatch(ctx context.Context, in *QueryBatchRequest, opts ...grpc.CallOption) (*QueryBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBatchResponse)
	err := c.cc.Invoke(ctx, PlasmodAPIService_QueryBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlasmodAPIServiceServer is the server API for PlasmodAPIService service.
// All implementations must embed UnimplementedPlasmodAPIServiceServer
// for forward compatibility.
//
// PlasmodAPIService exposes the same warm-segment ingest/query semantics as the HTTP JSON API.
// Default listen: PLASMOD_GRPC_ADDR (see app/ports.go). HTTP remains on :8080 / :19530.
type PlasmodAPIServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error)
	IngestVectors(context.Context, *IngestVectorsRequest) (*IngestVectorsResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	QueryBatch(context.Context, *QueryBatchRequest) (*QueryBatchResponse, error)
	mustEmbedUnimplementedPlasmodAPIServiceServer()
}

// UnimplementedPlasmodAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlasmodAPIServiceServer struct{}

func (UnimplementedPlasmodAPIServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPlasmodAPIServiceServer) IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestEvent not implemented")
}
func (UnimplementedPlasmodAPIServiceServer) IngestVectors(context.Context, *IngestVectorsRequest) (*IngestVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestVectors not implemented")
}
func (UnimplementedPlasmodAPIServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedPlasmodAPIServiceServer) QueryBatch(context.Context, *QueryBatchRequest) (*QueryBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryBatch not implemented")
}
func (UnimplementedPlasmodAPIServiceServer) mustEmbedUnimplementedPlasmodAPIServiceServer() {}
func (UnimplementedPlasmodAPIServiceServer) testEmbeddedByValue()                           {}

// UnsafePlasmodAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlasmodAPIServiceServer will
// result in compilation errors.
type UnsafePlasmodAPIServiceServer interface {
	mustEmbedUnimplementedPlasmodAPIServiceServer()
}

func RegisterPlasmodAPIServiceServer(s grpc.ServiceRegistrar, srv PlasmodAPIServiceServer) {
	// If the following call panics, it indicates UnimplementedPlasmodAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlasmodAPIService_ServiceDesc, srv)
}

func _PlasmodAPIService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlasmodAPIServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlasmodAPIService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlasmodAPIServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlasmodAPIService_IngestEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlasmodAPIServiceServer).IngestEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlasmodAPIService_IngestEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlasmodAPIServiceServer).IngestEvent(ctx, req.(*IngestEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlasmodAPIService_IngestVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlasmodAPIServiceServer).IngestVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlasmodAPIService_IngestVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlasmodAPIServiceServer).IngestVectors(ctx, req.(*IngestVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlasmodAPIService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlasmodAPIServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlasmodAPIService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlasmodAPIServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlasmodAPIService_QueryBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlasmodAPIServiceServer).QueryBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlasmodAPIService_QueryBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlasmodAPIServiceServer).QueryBatch(ctx, req.(*QueryBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlasmodAPIService_ServiceDesc is the grpc.ServiceDesc for PlasmodAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlasmodAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plasmod.v1.PlasmodAPIService",
	HandlerType: (*PlasmodAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _PlasmodAPIService_Health_Handler,
		},
		{
			MethodName: "IngestEvent",
			Handler:    _PlasmodAPIService_IngestEvent_Handler,
		},
		{
			MethodName: "IngestVectors",
			Handler:    _PlasmodAPIService_IngestVectors_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _PlasmodAPIService_Query_Handler,
		},
		{
			MethodName: "QueryBatch",
			Handler:    _PlasmodAPIService_QueryBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plasmod/v1/plasmod.proto",
}
