// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v7.34.1
// source: plasmod/v1/plasmod.proto

package plasmodv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Transport     string                 `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

type IngestEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventJson     string                 `protobuf:"bytes,1,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"` // full schemas.Event JSON (same as POST /v1/ingest/events)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{2}
}

func (x *IngestEventRequest) GetEventJson() string {
	if x != nil {
		return x.EventJson
	}
	return ""
}

type IngestEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckJson       string                 `protobuf:"bytes,1,opt,name=ack_json,json=ackJson,proto3" json:"ack_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{3}
}

func (x *IngestEventResponse) GetAckJson() string {
	if x != nil {
		return x.AckJson
	}
	return ""
}

type IngestVectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	ObjectIds     []string               `protobuf:"bytes,2,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	Vectors       []*VectorRow           `protobuf:"bytes,3,rep,name=vectors,proto3" json:"vectors,omitempty"`
	IndexType     string                 `protobuf:"bytes,4,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"` // HNSW, IVF_FLAT, IVF_PQ, IVF_SQ8, DISKANN
	IvfNlist      int32                  `protobuf:"varint,5,opt,name=ivf_nlist,json=ivfNlist,proto3" json:"ivf_nlist,omitempty"`
	IvfNprobe     int32                  `protobuf:"varint,6,opt,name=ivf_nprobe,json=ivfNprobe,proto3" json:"ivf_nprobe,omitempty"`
	IvfM          int32                  `protobuf:"varint,7,opt,name=ivf_m,json=ivfM,proto3" json:"ivf_m,omitempty"`
	IvfNbits      int32                  `protobuf:"varint,8,opt,name=ivf_nbits,json=ivfNbits,proto3" json:"ivf_nbits,omitempty"`
	IvfSqType     string                 `protobuf:"bytes,9,opt,name=ivf_sq_type,json=ivfSqType,proto3" json:"ivf_sq_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestVectorsRequest) Reset() {
	*x = IngestVectorsRequest{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestVectorsRequest) ProtoMessage() {}

func (x *IngestVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestVectorsRequest.ProtoReflect.Descriptor instead.
func (*IngestVectorsRequest) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{4}
}

func (x *IngestVectorsRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *IngestVectorsRequest) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *IngestVectorsRequest) GetVectors() []*VectorRow {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *IngestVectorsRequest) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *IngestVectorsRequest) GetIvfNlist() int32 {
	if x != nil {
		return x.IvfNlist
	}
	return 0
}

func (x *IngestVectorsRequest) GetIvfNprobe() int32 {
	if x != nil {
		return x.IvfNprobe
	}
	return 0
}

func (x *IngestVectorsRequest) GetIvfM() int32 {
	if x != nil {
		return x.IvfM
	}
	return 0
}

func (x *IngestVectorsRequest) GetIvfNbits() int32 {
	if x != nil {
		return x.IvfNbits
	}
	return 0
}

func (x *IngestVectorsRequest) GetIvfSqType() string {
	if x != nil {
		return x.IvfSqType
	}
	return ""
}

type IngestVectorsFlatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	ObjectIds     []string               `protobuf:"bytes,2,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	N             int32                  `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
	Dim           int32                  `protobuf:"varint,4,opt,name=dim,proto3" json:"dim,omitempty"`
	VectorsLe     []byte                 `protobuf:"bytes,5,opt,name=vectors_le,json=vectorsLe,proto3" json:"vectors_le,omitempty"` // n*dim float32 values, little-endian, row-major
	IndexType     string                 `protobuf:"bytes,6,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"` // HNSW, IVF_FLAT, IVF_PQ, IVF_SQ8, DISKANN
	IvfNlist      int32                  `protobuf:"varint,7,opt,name=ivf_nlist,json=ivfNlist,proto3" json:"ivf_nlist,omitempty"`
	IvfNprobe     int32                  `protobuf:"varint,8,opt,name=ivf_nprobe,json=ivfNprobe,proto3" json:"ivf_nprobe,omitempty"`
	IvfM          int32                  `protobuf:"varint,9,opt,name=ivf_m,json=ivfM,proto3" json:"ivf_m,omitempty"`
	IvfNbits      int32                  `protobuf:"varint,10,opt,name=ivf_nbits,json=ivfNbits,proto3" json:"ivf_nbits,omitempty"`
	IvfSqType     string                 `protobuf:"bytes,11,opt,name=ivf_sq_type,json=ivfSqType,proto3" json:"ivf_sq_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestVectorsFlatRequest) Reset() {
	*x = IngestVectorsFlatRequest{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestVectorsFlatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestVectorsFlatRequest) ProtoMessage() {}

func (x *IngestVectorsFlatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestVectorsFlatRequest.ProtoReflect.Descriptor instead.
func (*IngestVectorsFlatRequest) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{5}
}

func (x *IngestVectorsFlatRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *IngestVectorsFlatRequest) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *IngestVectorsFlatRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *IngestVectorsFlatRequest) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *IngestVectorsFlatRequest) GetVectorsLe() []byte {
	if x != nil {
		return x.VectorsLe
	}
	return nil
}

func (x *IngestVectorsFlatRequest) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *IngestVectorsFlatRequest) GetIvfNlist() int32 {
	if x != nil {
		return x.IvfNlist
	}
	return 0
}

func (x *IngestVectorsFlatRequest) GetIvfNprobe() int32 {
	if x != nil {
		return x.IvfNprobe
	}
	return 0
}

func (x *IngestVectorsFlatRequest) GetIvfM() int32 {
	if x != nil {
		return x.IvfM
	}
	return 0
}

func (x *IngestVectorsFlatRequest) GetIvfNbits() int32 {
	if x != nil {
		return x.IvfNbits
	}
	return 0
}

func (x *IngestVectorsFlatRequest) GetIvfSqType() string {
	if x != nil {
		return x.IvfSqType
	}
	return ""
}

type VectorRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorRow) Reset() {
	*x = VectorRow{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorRow) ProtoMessage() {}

func (x *VectorRow) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorRow.ProtoReflect.Descriptor instead.
func (*VectorRow) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{6}
}

func (x *VectorRow) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type IngestVectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SegmentId     string                 `protobuf:"bytes,2,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Ingested      int32                  `protobuf:"varint,3,opt,name=ingested,proto3" json:"ingested,omitempty"`
	VectorDim     int32                  `protobuf:"varint,4,opt,name=vector_dim,json=vectorDim,proto3" json:"vector_dim,omitempty"`
	IndexType     string                 `protobuf:"bytes,5,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`
	DirectWarm    bool                   `protobuf:"varint,6,opt,name=direct_warm,json=directWarm,proto3" json:"direct_warm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestVectorsResponse) Reset() {
	*x = IngestVectorsResponse{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestVectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestVectorsResponse) ProtoMessage() {}

func (x *IngestVectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestVectorsResponse.ProtoReflect.Descriptor instead.
func (*IngestVectorsResponse) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{7}
}

func (x *IngestVectorsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestVectorsResponse) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *IngestVectorsResponse) GetIngested() int32 {
	if x != nil {
		return x.Ingested
	}
	return 0
}

func (x *IngestVectorsResponse) GetVectorDim() int32 {
	if x != nil {
		return x.VectorDim
	}
	return 0
}

func (x *IngestVectorsResponse) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *IngestVectorsResponse) GetDirectWarm() bool {
	if x != nil {
		return x.DirectWarm
	}
	return false
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryJson     string                 `protobuf:"bytes,1,opt,name=query_json,json=queryJson,proto3" json:"query_json,omitempty"` // full schemas.QueryRequest JSON (POST /v1/query)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{8}
}

func (x *QueryRequest) GetQueryJson() string {
	if x != nil {
		return x.QueryJson
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{9}
}

func (x *QueryResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type QueryBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentMode     string                 `protobuf:"bytes,1,opt,name=agent_mode,json=agentMode,proto3" json:"agent_mode,omitempty"`
	WarmSegmentId string                 `protobuf:"bytes,2,opt,name=warm_segment_id,json=warmSegmentId,proto3" json:"warm_segment_id,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Vectors       []*VectorRow           `protobuf:"bytes,4,rep,name=vectors,proto3" json:"vectors,omitempty"`
	SourceIds     []string               `protobuf:"bytes,5,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	RowLineage    []*RowLineage          `protobuf:"bytes,6,rep,name=row_lineage,json=rowLineage,proto3" json:"row_lineage,omitempty"`
	SearchRaw     bool                   `protobuf:"varint,7,opt,name=search_raw,json=searchRaw,proto3" json:"search_raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBatchRequest) Reset() {
	*x = QueryBatchRequest{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBatchRequest) ProtoMessage() {}

func (x *QueryBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBatchRequest.ProtoReflect.Descriptor instead.
func (*QueryBatchRequest) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{10}
}

func (x *QueryBatchRequest) GetAgentMode() string {
	if x != nil {
		return x.AgentMode
	}
	return ""
}

func (x *QueryBatchRequest) GetWarmSegmentId() string {
	if x != nil {
		return x.WarmSegmentId
	}
	return ""
}

func (x *QueryBatchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QueryBatchRequest) GetVectors() []*VectorRow {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *QueryBatchRequest) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *QueryBatchRequest) GetRowLineage() []*RowLineage {
	if x != nil {
		return x.RowLineage
	}
	return nil
}

func (x *QueryBatchRequest) GetSearchRaw() bool {
	if x != nil {
		return x.SearchRaw
	}
	return false
}

type RowLineage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceIndices []int32                `protobuf:"varint,1,rep,packed,name=source_indices,json=sourceIndices,proto3" json:"source_indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowLineage) Reset() {
	*x = RowLineage{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowLineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowLineage) ProtoMessage() {}

func (x *RowLineage) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowLineage.ProtoReflect.Descriptor instead.
func (*RowLineage) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{11}
}

func (x *RowLineage) GetSourceIndices() []int32 {
	if x != nil {
		return x.SourceIndices
	}
	return nil
}

type QueryBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AgentMode     string                 `protobuf:"bytes,2,opt,name=agent_mode,json=agentMode,proto3" json:"agent_mode,omitempty"`
	WarmSegmentId string                 `protobuf:"bytes,3,opt,name=warm_segment_id,json=warmSegmentId,proto3" json:"warm_segment_id,omitempty"`
	SourceIds     []string               `protobuf:"bytes,4,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	Rows          []*QueryBatchRow       `protobuf:"bytes,5,rep,name=rows,proto3" json:"rows,omitempty"`
	BySource      map[string]*StringList `protobuf:"bytes,6,rep,name=by_source,json=bySource,proto3" json:"by_source,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBatchResponse) Reset() {
	*x = QueryBatchResponse{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBatchResponse) ProtoMessage() {}

func (x *QueryBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBatchResponse.ProtoReflect.Descriptor instead.
func (*QueryBatchResponse) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{12}
}

func (x *QueryBatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryBatchResponse) GetAgentMode() string {
	if x != nil {
		return x.AgentMode
	}
	return ""
}

func (x *QueryBatchResponse) GetWarmSegmentId() string {
	if x != nil {
		return x.WarmSegmentId
	}
	return ""
}

func (x *QueryBatchResponse) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *QueryBatchResponse) GetRows() []*QueryBatchRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryBatchResponse) GetBySource() map[string]*StringList {
	if x != nil {
		return x.BySource
	}
	return nil
}

type QueryBatchFlatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarmSegmentId string                 `protobuf:"bytes,1,opt,name=warm_segment_id,json=warmSegmentId,proto3" json:"warm_segment_id,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Nq            int32                  `protobuf:"varint,3,opt,name=nq,proto3" json:"nq,omitempty"`
	Dim           int32                  `protobuf:"varint,4,opt,name=dim,proto3" json:"dim,omitempty"`
	QueriesLe     []byte                 `protobuf:"bytes,5,opt,name=queries_le,json=queriesLe,proto3" json:"queries_le,omitempty"`  // nq*dim float32 values, little-endian, row-major
	SearchRaw     bool                   `protobuf:"varint,6,opt,name=search_raw,json=searchRaw,proto3" json:"search_raw,omitempty"` // bypass Plasmod reorder/plugin path
	Serial        bool                   `protobuf:"varint,7,opt,name=serial,proto3" json:"serial,omitempty"`                        // preserve single-query behavior while amortizing transport
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBatchFlatRequest) Reset() {
	*x = QueryBatchFlatRequest{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBatchFlatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBatchFlatRequest) ProtoMessage() {}

func (x *QueryBatchFlatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBatchFlatRequest.ProtoReflect.Descriptor instead.
func (*QueryBatchFlatRequest) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{13}
}

func (x *QueryBatchFlatRequest) GetWarmSegmentId() string {
	if x != nil {
		return x.WarmSegmentId
	}
	return ""
}

func (x *QueryBatchFlatRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QueryBatchFlatRequest) GetNq() int32 {
	if x != nil {
		return x.Nq
	}
	return 0
}

func (x *QueryBatchFlatRequest) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *QueryBatchFlatRequest) GetQueriesLe() []byte {
	if x != nil {
		return x.QueriesLe
	}
	return nil
}

func (x *QueryBatchFlatRequest) GetSearchRaw() bool {
	if x != nil {
		return x.SearchRaw
	}
	return false
}

func (x *QueryBatchFlatRequest) GetSerial() bool {
	if x != nil {
		return x.Serial
	}
	return false
}

type QueryBatchFlatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	WarmSegmentId string                 `protobuf:"bytes,2,opt,name=warm_segment_id,json=warmSegmentId,proto3" json:"warm_segment_id,omitempty"`
	Nq            int32                  `protobuf:"varint,3,opt,name=nq,proto3" json:"nq,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Dim           int32                  `protobuf:"varint,5,opt,name=dim,proto3" json:"dim,omitempty"`
	IdsLe         []byte                 `protobuf:"bytes,6,opt,name=ids_le,json=idsLe,proto3" json:"ids_le,omitempty"`                   // nq*top_k int64 values, little-endian, row-major
	DistancesLe   []byte                 `protobuf:"bytes,7,opt,name=distances_le,json=distancesLe,proto3" json:"distances_le,omitempty"` // nq*top_k float32 values, little-endian, row-major
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBatchFlatResponse) Reset() {
	*x = QueryBatchFlatResponse{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBatchFlatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBatchFlatResponse) ProtoMessage() {}

func (x *QueryBatchFlatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBatchFlatResponse.ProtoReflect.Descriptor instead.
func (*QueryBatchFlatResponse) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{14}
}

func (x *QueryBatchFlatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryBatchFlatResponse) GetWarmSegmentId() string {
	if x != nil {
		return x.WarmSegmentId
	}
	return ""
}

func (x *QueryBatchFlatResponse) GetNq() int32 {
	if x != nil {
		return x.Nq
	}
	return 0
}

func (x *QueryBatchFlatResponse) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *QueryBatchFlatResponse) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *QueryBatchFlatResponse) GetIdsLe() []byte {
	if x != nil {
		return x.IdsLe
	}
	return nil
}

func (x *QueryBatchFlatResponse) GetDistancesLe() []byte {
	if x != nil {
		return x.DistancesLe
	}
	return nil
}

type QueryBatchRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowIndex      int32                  `protobuf:"varint,1,opt,name=row_index,json=rowIndex,proto3" json:"row_index,omitempty"`
	ObjectIds     []string               `protobuf:"bytes,2,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	Distances     []float32              `protobuf:"fixed32,3,rep,packed,name=distances,proto3" json:"distances,omitempty"`
	SourceRefs    []int32                `protobuf:"varint,4,rep,packed,name=source_refs,json=sourceRefs,proto3" json:"source_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBatchRow) Reset() {
	*x = QueryBatchRow{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBatchRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBatchRow) ProtoMessage() {}

func (x *QueryBatchRow) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBatchRow.ProtoReflect.Descriptor instead.
func (*QueryBatchRow) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{15}
}

func (x *QueryBatchRow) GetRowIndex() int32 {
	if x != nil {
		return x.RowIndex
	}
	return 0
}

func (x *QueryBatchRow) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *QueryBatchRow) GetDistances() []float32 {
	if x != nil {
		return x.Distances
	}
	return nil
}

func (x *QueryBatchRow) GetSourceRefs() []int32 {
	if x != nil {
		return x.SourceRefs
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_plasmod_v1_plasmod_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_plasmod_v1_plasmod_proto_rawDescGZIP(), []int{16}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_plasmod_v1_plasmod_proto protoreflect.FileDescriptor

const file_plasmod_v1_plasmod_proto_rawDesc = "" +
	"\n" +
	"\x18plasmod/v1/plasmod.proto\x12\n" +
	"plasmod.v1\"\x0f\n" +
	"\rHealthRequest\"F\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\"3\n" +
	"\x12IngestEventRequest\x12\x1d\n" +
	"\n" +
	"event_json\x18\x01 \x01(\tR\teventJson\"0\n" +
	"\x13IngestEventResponse\x12\x19\n" +
	"\back_json\x18\x01 \x01(\tR\aackJson\"\xb2\x02\n" +
	"\x14IngestVectorsRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x02 \x03(\tR\tobjectIds\x12/\n" +
	"\avectors\x18\x03 \x03(\v2\x15.plasmod.v1.VectorRowR\avectors\x12\x1d\n" +
	"\n" +
	"index_type\x18\x04 \x01(\tR\tindexType\x12\x1b\n" +
	"\tivf_nlist\x18\x05 \x01(\x05R\bivfNlist\x12\x1d\n" +
	"\n" +
	"ivf_nprobe\x18\x06 \x01(\x05R\tivfNprobe\x12\x13\n" +
	"\x05ivf_m\x18\a \x01(\x05R\x04ivfM\x12\x1b\n" +
	"\tivf_nbits\x18\b \x01(\x05R\bivfNbits\x12\x1e\n" +
	"\vivf_sq_type\x18\t \x01(\tR\tivfSqType\"\xc4\x02\n" +
	"\x18IngestVectorsFlatRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x02 \x03(\tR\tobjectIds\x12\f\n" +
	"\x01n\x18\x03 \x01(\x05R\x01n\x12\x10\n" +
	"\x03dim\x18\x04 \x01(\x05R\x03dim\x12\x1d\n" +
	"\n" +
	"vectors_le\x18\x05 \x01(\fR\tvectorsLe\x12\x1d\n" +
	"\n" +
	"index_type\x18\x06 \x01(\tR\tindexType\x12\x1b\n" +
	"\tivf_nlist\x18\a \x01(\x05R\bivfNlist\x12\x1d\n" +
	"\n" +
	"ivf_nprobe\x18\b \x01(\x05R\tivfNprobe\x12\x13\n" +
	"\x05ivf_m\x18\t \x01(\x05R\x04ivfM\x12\x1b\n" +
	"\tivf_nbits\x18\n" +
	" \x01(\x05R\bivfNbits\x12\x1e\n" +
	"\vivf_sq_type\x18\v \x01(\tR\tivfSqType\"#\n" +
	"\tVectorRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xc9\x01\n" +
	"\x15IngestVectorsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x02 \x01(\tR\tsegmentId\x12\x1a\n" +
	"\bingested\x18\x03 \x01(\x05R\bingested\x12\x1d\n" +
	"\n" +
	"vector_dim\x18\x04 \x01(\x05R\tvectorDim\x12\x1d\n" +
	"\n" +
	"index_type\x18\x05 \x01(\tR\tindexType\x12\x1f\n" +
	"\vdirect_warm\x18\x06 \x01(\bR\n" +
	"directWarm\"-\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"query_json\x18\x01 \x01(\tR\tqueryJson\"0\n" +
	"\rQueryResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\"\x97\x02\n" +
	"\x11QueryBatchRequest\x12\x1d\n" +
	"\n" +
	"agent_mode\x18\x01 \x01(\tR\tagentMode\x12&\n" +
	"\x0fwarm_segment_id\x18\x02 \x01(\tR\rwarmSegmentId\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12/\n" +
	"\avectors\x18\x04 \x03(\v2\x15.plasmod.v1.VectorRowR\avectors\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x05 \x03(\tR\tsourceIds\x127\n" +
	"\vrow_lineage\x18\x06 \x03(\v2\x16.plasmod.v1.RowLineageR\n" +
	"rowLineage\x12\x1d\n" +
	"\n" +
	"search_raw\x18\a \x01(\bR\tsearchRaw\"3\n" +
	"\n" +
	"RowLineage\x12%\n" +
	"\x0esource_indices\x18\x01 \x03(\x05R\rsourceIndices\"\xe1\x02\n" +
	"\x12QueryBatchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"agent_mode\x18\x02 \x01(\tR\tagentMode\x12&\n" +
	"\x0fwarm_segment_id\x18\x03 \x01(\tR\rwarmSegmentId\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x04 \x03(\tR\tsourceIds\x12-\n" +
	"\x04rows\x18\x05 \x03(\v2\x19.plasmod.v1.QueryBatchRowR\x04rows\x12I\n" +
	"\tby_source\x18\x06 \x03(\v2,.plasmod.v1.QueryBatchResponse.BySourceEntryR\bbySource\x1aS\n" +
	"\rBySourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.plasmod.v1.StringListR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x15QueryBatchFlatRequest\x12&\n" +
	"\x0fwarm_segment_id\x18\x01 \x01(\tR\rwarmSegmentId\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12\x0e\n" +
	"\x02nq\x18\x03 \x01(\x05R\x02nq\x12\x10\n" +
	"\x03dim\x18\x04 \x01(\x05R\x03dim\x12\x1d\n" +
	"\n" +
	"queries_le\x18\x05 \x01(\fR\tqueriesLe\x12\x1d\n" +
	"\n" +
	"search_raw\x18\x06 \x01(\bR\tsearchRaw\x12\x16\n" +
	"\x06serial\x18\a \x01(\bR\x06serial\"\xc9\x01\n" +
	"\x16QueryBatchFlatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12&\n" +
	"\x0fwarm_segment_id\x18\x02 \x01(\tR\rwarmSegmentId\x12\x0e\n" +
	"\x02nq\x18\x03 \x01(\x05R\x02nq\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x12\x10\n" +
	"\x03dim\x18\x05 \x01(\x05R\x03dim\x12\x15\n" +
	"\x06ids_le\x18\x06 \x01(\fR\x05idsLe\x12!\n" +
	"\fdistances_le\x18\a \x01(\fR\vdistancesLe\"\x8a\x01\n" +
	"\rQueryBatchRow\x12\x1b\n" +
	"\trow_index\x18\x01 \x01(\x05R\browIndex\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x02 \x03(\tR\tobjectIds\x12\x1c\n" +
	"\tdistances\x18\x03 \x03(\x02R\tdistances\x12\x1f\n" +
	"\vsource_refs\x18\x04 \x03(\x05R\n" +
	"sourceRefs\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2\xbc\x04\n" +
	"\x11PlasmodAPIService\x12?\n" +
	"\x06Health\x12\x19.plasmod.v1.HealthRequest\x1a\x1a.plasmod.v1.HealthResponse\x12N\n" +
	"\vIngestEvent\x12\x1e.plasmod.v1.IngestEventRequest\x1a\x1f.plasmod.v1.IngestEventResponse\x12T\n" +
	"\rIngestVectors\x12 .plasmod.v1.IngestVectorsRequest\x1a!.plasmod.v1.IngestVectorsResponse\x12\\\n" +
	"\x11IngestVectorsFlat\x12$.plasmod.v1.IngestVectorsFlatRequest\x1a!.plasmod.v1.IngestVectorsResponse\x12<\n" +
	"\x05Query\x12\x18.plasmod.v1.QueryRequest\x1a\x19.plasmod.v1.QueryResponse\x12K\n" +
	"\n" +
	"QueryBatch\x12\x1d.plasmod.v1.QueryBatchRequest\x1a\x1e.plasmod.v1.QueryBatchResponse\x12W\n" +
	"\x0eQueryBatchFlat\x12!.plasmod.v1.QueryBatchFlatRequest\x1a\".plasmod.v1.QueryBatchFlatResponseB7Z5plasmod/src/internal/api/grpc/pb/plasmod/v1;plasmodv1b\x06proto3"

var (
	file_plasmod_v1_plasmod_proto_rawDescOnce sync.Once
	file_plasmod_v1_plasmod_proto_rawDescData []byte
)

func file_plasmod_v1_plasmod_proto_rawDescGZIP() []byte {
	file_plasmod_v1_plasmod_proto_rawDescOnce.Do(func() {
		file_plasmod_v1_plasmod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plasmod_v1_plasmod_proto_rawDesc), len(file_plasmod_v1_plasmod_proto_rawDesc)))
	})
	return file_plasmod_v1_plasmod_proto_rawDescData
}

var file_plasmod_v1_plasmod_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_plasmod_v1_plasmod_proto_goTypes = []any{
	(*HealthRequest)(nil),            // 0: plasmod.v1.HealthRequest
	(*HealthResponse)(nil),           // 1: plasmod.v1.HealthResponse
	(*IngestEventRequest)(nil),       // 2: plasmod.v1.IngestEventRequest
	(*IngestEventResponse)(nil),      // 3: plasmod.v1.IngestEventResponse
	(*IngestVectorsRequest)(nil),     // 4: plasmod.v1.IngestVectorsRequest
	(*IngestVectorsFlatRequest)(nil), // 5: plasmod.v1.IngestVectorsFlatRequest
	(*VectorRow)(nil),                // 6: plasmod.v1.VectorRow
	(*IngestVectorsResponse)(nil),    // 7: plasmod.v1.IngestVectorsResponse
	(*QueryRequest)(nil),             // 8: plasmod.v1.QueryRequest
	(*QueryResponse)(nil),            // 9: plasmod.v1.QueryResponse
	(*QueryBatchRequest)(nil),        // 10: plasmod.v1.QueryBatchRequest
	(*RowLineage)(nil),               // 11: plasmod.v1.RowLineage
	(*QueryBatchResponse)(nil),       // 12: plasmod.v1.QueryBatchResponse
	(*QueryBatchFlatRequest)(nil),    // 13: plasmod.v1.QueryBatchFlatRequest
	(*QueryBatchFlatResponse)(nil),   // 14: plasmod.v1.QueryBatchFlatResponse
	(*QueryBatchRow)(nil),            // 15: plasmod.v1.QueryBatchRow
	(*StringList)(nil),               // 16: plasmod.v1.StringList
	nil,                              // 17: plasmod.v1.QueryBatchResponse.BySourceEntry
}
var file_plasmod_v1_plasmod_proto_depIdxs = []int32{
	6,  // 0: plasmod.v1.IngestVectorsRequest.vectors:type_name -> plasmod.v1.VectorRow
	6,  // 1: plasmod.v1.QueryBatchRequest.vectors:type_name -> plasmod.v1.VectorRow
	11, // 2: plasmod.v1.QueryBatchRequest.row_lineage:type_name -> plasmod.v1.RowLineage
	15, // 3: plasmod.v1.QueryBatchResponse.rows:type_name -> plasmod.v1.QueryBatchRow
	17, // 4: plasmod.v1.QueryBatchResponse.by_source:type_name -> plasmod.v1.QueryBatchResponse.BySourceEntry
	16, // 5: plasmod.v1.QueryBatchResponse.BySourceEntry.value:type_name -> plasmod.v1.StringList
	0,  // 6: plasmod.v1.PlasmodAPIService.Health:input_type -> plasmod.v1.HealthRequest
	2,  // 7: plasmod.v1.PlasmodAPIService.IngestEvent:input_type -> plasmod.v1.IngestEventRequest
	4,  // 8: plasmod.v1.PlasmodAPIService.IngestVectors:input_type -> plasmod.v1.IngestVectorsRequest
	5,  // 9: plasmod.v1.PlasmodAPIService.IngestVectorsFlat:input_type -> plasmod.v1.IngestVectorsFlatRequest
	8,  // 10: plasmod.v1.PlasmodAPIService.Query:input_type -> plasmod.v1.QueryRequest
	10, // 11: plasmod.v1.PlasmodAPIService.QueryBatch:input_type -> plasmod.v1.QueryBatchRequest
	13, // 12: plasmod.v1.PlasmodAPIService.QueryBatchFlat:input_type -> plasmod.v1.QueryBatchFlatRequest
	1,  // 13: plasmod.v1.PlasmodAPIService.Health:output_type -> plasmod.v1.HealthResponse
	3,  // 14: plasmod.v1.PlasmodAPIService.IngestEvent:output_type -> plasmod.v1.IngestEventResponse
	7,  // 15: plasmod.v1.PlasmodAPIService.IngestVectors:output_type -> plasmod.v1.IngestVectorsResponse
	7,  // 16: plasmod.v1.PlasmodAPIService.IngestVectorsFlat:output_type -> plasmod.v1.IngestVectorsResponse
	9,  // 17: plasmod.v1.PlasmodAPIService.Query:output_type -> plasmod.v1.QueryResponse
	12, // 18: plasmod.v1.PlasmodAPIService.QueryBatch:output_type -> plasmod.v1.QueryBatchResponse
	14, // 19: plasmod.v1.PlasmodAPIService.QueryBatchFlat:output_type -> plasmod.v1.QueryBatchFlatResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plasmod_v1_plasmod_proto_init() }
func file_plasmod_v1_plasmod_proto_init() {
	if File_plasmod_v1_plasmod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plasmod_v1_plasmod_proto_rawDesc), len(file_plasmod_v1_plasmod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plasmod_v1_plasmod_proto_goTypes,
		DependencyIndexes: file_plasmod_v1_plasmod_proto_depIdxs,
		MessageInfos:      file_plasmod_v1_plasmod_proto_msgTypes,
	}.Build()
	File_plasmod_v1_plasmod_proto = out.File
	file_plasmod_v1_plasmod_proto_goTypes = nil
	file_plasmod_v1_plasmod_proto_depIdxs = nil
}
