package access

import (
	"encoding/json"
	"fmt"
	"net/http"
	"path"
	"strconv"
	"time"

	"andb/src/internal/s3util"
	"github.com/hamba/avro/v2"
)

func (g *Gateway) handleS3SnapshotExport(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	ctx := r.Context()

	s3Cfg, err := s3util.LoadFromEnv()
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// We use S3_PREFIX as "root" for all snapshot/segment objects.
	rootPath := s3Cfg.Prefix
	if rootPath != "" {
		// s3util treats endpoint as host:port; here we only care about object keys.
		for len(rootPath) > 0 && rootPath[0] == '/' {
			rootPath = rootPath[1:]
		}
	}

	// Stable IDs for dev export.
	collectionID := int64(100)
	snapshotID := int64(time.Now().Unix())
	segmentID := int64(1001)

	manifestDir := path.Join(rootPath, "snapshots", strconv.FormatInt(collectionID, 10), "manifests", strconv.FormatInt(snapshotID, 10))
	metadataPath := path.Join(rootPath, "snapshots", strconv.FormatInt(collectionID, 10), "metadata", strconv.FormatInt(snapshotID, 10)+".json")
	manifestPath := path.Join(manifestDir, strconv.FormatInt(segmentID, 10)+".avro")
	segmentDataPath := path.Join(rootPath, "segments", strconv.FormatInt(collectionID, 10), strconv.FormatInt(segmentID, 10), "segment_data.json")

	manifestRec := buildManifestEntry(segmentID)
	manifestSchema, err := avro.Parse(snapshotManifestSchemaJSON)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	manifestBytes, err := avro.Marshal(manifestSchema, manifestRec)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	// Validate the generated bytes can be decoded by the same schema.
	var decoded manifestEntry
	if err := avro.Unmarshal(manifestSchema, manifestBytes, &decoded); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	metadata := map[string]any{
		"format_version": int32(1),
		"snapshot_info": map[string]any{
			"id":            snapshotID,
			"collection_id": collectionID,
			"create_ts":     time.Now().Unix(),
			"name":          fmt.Sprintf("snapshot_%d", snapshotID),
			"description":   "s3 snapshot export from local runtime",
			"s3_location":   metadataPath,
			"partition_ids": []int64{1},
		},
		"collection": map[string]any{
			"name": "cogdb_local",
		},
		"indexes":                 []any{},
		"manifest_list":           []string{manifestPath},
		"storagev2_manifest_list": []any{},
		"segment_ids":             []int64{segmentID},
		"index_ids":               []int64{},
		// Extra field so we can demonstrate "segment storage" alongside snapshot metadata.
		"segment_data": segmentDataPath,
	}

	// PUT metadata + manifest + segment data and verify round-trip via GET.
	_, metadataRT, err := s3util.PutBytesAndVerify(ctx, http.DefaultClient, s3Cfg, metadataPath, mustJSONBytes(metadata), "application/json")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	_, manifestRT, err := s3util.PutBytesAndVerify(ctx, http.DefaultClient, s3Cfg, manifestPath, manifestBytes, "application/octet-stream")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	segmentData := map[string]any{
		"segment_id":    segmentID,
		"collection_id": collectionID,
		"payload":       "placeholder",
		"generated_at":  time.Now().UTC().Format(time.RFC3339),
	}
	_, segmentRT, err := s3util.PutBytesAndVerify(ctx, http.DefaultClient, s3Cfg, segmentDataPath, mustJSONBytes(segmentData), "application/json")
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]any{
		"status":            "ok",
		"bucket":            s3Cfg.Bucket,
		"root_path":         rootPath,
		"snapshot_id":       snapshotID,
		"collection_id":     collectionID,
		"segment_id":        segmentID,
		"metadata_path":     metadataPath,
		"manifest_path":     manifestPath,
		"segment_data_path": segmentDataPath,
		"roundtrip_ok": map[string]bool{
			"metadata":     metadataRT,
			"manifest":     manifestRT,
			"segment_data": segmentRT,
		},
	})
}

type manifestEntry struct {
	SegmentID         int64                       `avro:"segment_id"`
	PartitionID       int64                       `avro:"partition_id"`
	SegmentLevel      int64                       `avro:"segment_level"`
	BinlogFiles       []manifestFieldBinlog       `avro:"binlog_files"`
	DeltalogFiles     []manifestFieldBinlog       `avro:"deltalog_files"`
	IndexFiles        []manifestIndexFile         `avro:"index_files"`
	ChannelName       string                      `avro:"channel_name"`
	NumOfRows         int64                       `avro:"num_of_rows"`
	StatslogFiles     []manifestFieldBinlog       `avro:"statslog_files"`
	Bm25StatslogFiles []manifestFieldBinlog       `avro:"bm25_statslog_files"`
	TextIndexFiles    []manifestTextIndexEntry    `avro:"text_index_files"`
	JsonKeyIndexFiles []manifestJsonKeyIndexEntry `avro:"json_key_index_files"`
	StartPosition     manifestMsgPosition         `avro:"start_position"`
	DmlPosition       manifestMsgPosition         `avro:"dml_position"`
	StorageVersion    int64                       `avro:"storage_version"`
	IsSorted          bool                        `avro:"is_sorted"`
}

type manifestFieldBinlog struct {
	FieldID int64            `avro:"field_id"`
	Binlogs []manifestBinlog `avro:"binlogs"`
}

type manifestBinlog struct {
	EntriesNum    int64  `avro:"entries_num"`
	TimestampFrom int64  `avro:"timestamp_from"`
	TimestampTo   int64  `avro:"timestamp_to"`
	LogPath       string `avro:"log_path"`
	LogSize       int64  `avro:"log_size"`
	LogID         int64  `avro:"log_id"`
	MemorySize    int64  `avro:"memory_size"`
}

type manifestIndexFile struct {
	SegmentID                 int64              `avro:"segment_id"`
	FieldID                   int64              `avro:"field_id"`
	IndexID                   int64              `avro:"index_id"`
	BuildID                   int64              `avro:"build_id"`
	IndexName                 string             `avro:"index_name"`
	IndexParams               []manifestKeyValue `avro:"index_params"`
	IndexFilePaths            []string           `avro:"index_file_paths"`
	SerializedSize            int64              `avro:"serialized_size"`
	IndexVersion              int64              `avro:"index_version"`
	NumRows                   int64              `avro:"num_rows"`
	CurrentIndexVersion       int32              `avro:"current_index_version"`
	CurrentScalarIndexVersion int32              `avro:"current_scalar_index_version"`
	MemSize                   int64              `avro:"mem_size"`
}

type manifestKeyValue struct {
	Key   string `avro:"key"`
	Value string `avro:"value"`
}

type manifestMsgPosition struct {
	ChannelName string `avro:"channel_name"`
	MsgID       []byte `avro:"msg_id"`
	MsgGroup    string `avro:"msg_group"`
	Timestamp   int64  `avro:"timestamp"`
}

type manifestTextIndexEntry struct {
	FieldID int64                  `avro:"field_id"`
	Stats   manifestTextIndexStats `avro:"stats"`
}

type manifestTextIndexStats struct {
	FieldID    int64    `avro:"field_id"`
	Version    int64    `avro:"version"`
	Files      []string `avro:"files"`
	LogSize    int64    `avro:"log_size"`
	MemorySize int64    `avro:"memory_size"`
	BuildID    int64    `avro:"build_id"`
}

type manifestJsonKeyIndexEntry struct {
	FieldID int64                `avro:"field_id"`
	Stats   manifestJsonKeyStats `avro:"stats"`
}

type manifestJsonKeyStats struct {
	FieldID                int64    `avro:"field_id"`
	Version                int64    `avro:"version"`
	Files                  []string `avro:"files"`
	LogSize                int64    `avro:"log_size"`
	MemorySize             int64    `avro:"memory_size"`
	BuildID                int64    `avro:"build_id"`
	JsonKeyStatsDataFormat int64    `avro:"json_key_stats_data_format"`
}

func buildManifestEntry(segmentID int64) manifestEntry {
	return manifestEntry{
		SegmentID:         segmentID,
		PartitionID:       1,
		SegmentLevel:      1,
		BinlogFiles:       []manifestFieldBinlog{},
		DeltalogFiles:     []manifestFieldBinlog{},
		IndexFiles:        []manifestIndexFile{},
		ChannelName:       "by-dev-export",
		NumOfRows:         100,
		StatslogFiles:     []manifestFieldBinlog{},
		Bm25StatslogFiles: []manifestFieldBinlog{},
		TextIndexFiles:    []manifestTextIndexEntry{},
		JsonKeyIndexFiles: []manifestJsonKeyIndexEntry{},
		StartPosition: manifestMsgPosition{
			ChannelName: "",
			MsgID:       []byte{},
			MsgGroup:    "",
			Timestamp:   0,
		},
		DmlPosition: manifestMsgPosition{
			ChannelName: "",
			MsgID:       []byte{},
			MsgGroup:    "",
			Timestamp:   0,
		},
		StorageVersion: 1,
		IsSorted:       false,
	}
}

const snapshotManifestSchemaJSON = `{
  "type": "record",
  "name": "ManifestEntry",
  "fields": [
    {"name":"segment_id","type":"long"},
    {"name":"partition_id","type":"long"},
    {"name":"segment_level","type":"long"},
    {"name":"binlog_files","type":{"type":"array","items":{"type":"record","name":"AvroFieldBinlog","fields":[
      {"name":"field_id","type":"long"},
      {"name":"binlogs","type":{"type":"array","items":{"type":"record","name":"AvroBinlog","fields":[
        {"name":"entries_num","type":"long"},
        {"name":"timestamp_from","type":"long"},
        {"name":"timestamp_to","type":"long"},
        {"name":"log_path","type":"string"},
        {"name":"log_size","type":"long"},
        {"name":"log_id","type":"long"},
        {"name":"memory_size","type":"long"}
      ]}}}
    ]}}},
    {"name":"deltalog_files","type":{"type":"array","items":"AvroFieldBinlog"}},
    {"name":"index_files","type":{"type":"array","items":{"type":"record","name":"AvroIndexFilePathInfo","fields":[
      {"name":"segment_id","type":"long"},
      {"name":"field_id","type":"long"},
      {"name":"index_id","type":"long"},
      {"name":"build_id","type":"long"},
      {"name":"index_name","type":"string"},
      {"name":"index_params","type":{"type":"array","items":{"type":"record","name":"AvroKeyValuePair","fields":[
        {"name":"key","type":"string"},
        {"name":"value","type":"string"}
      ]}}},
      {"name":"index_file_paths","type":{"type":"array","items":"string"}},
      {"name":"serialized_size","type":"long"},
      {"name":"index_version","type":"long"},
      {"name":"num_rows","type":"long"},
      {"name":"current_index_version","type":"int"},
      {"name":"current_scalar_index_version","type":"int"},
      {"name":"mem_size","type":"long"}
    ]}}},
    {"name":"channel_name","type":"string"},
    {"name":"num_of_rows","type":"long"},
    {"name":"statslog_files","type":{"type":"array","items":"AvroFieldBinlog"}},
    {"name":"bm25_statslog_files","type":{"type":"array","items":"AvroFieldBinlog"}},
    {"name":"text_index_files","type":{"type":"array","items":{"type":"record","name":"AvroTextIndexEntry","fields":[
      {"name":"field_id","type":"long"},
      {"name":"stats","type":{"type":"record","name":"AvroTextIndexStats","fields":[
        {"name":"field_id","type":"long"},
        {"name":"version","type":"long"},
        {"name":"files","type":{"type":"array","items":"string"}},
        {"name":"log_size","type":"long"},
        {"name":"memory_size","type":"long"},
        {"name":"build_id","type":"long"}
      ]}}
    ]}}},
    {"name":"json_key_index_files","type":{"type":"array","items":{"type":"record","name":"AvroJsonKeyIndexEntry","fields":[
      {"name":"field_id","type":"long"},
      {"name":"stats","type":{"type":"record","name":"AvroJsonKeyStats","fields":[
        {"name":"field_id","type":"long"},
        {"name":"version","type":"long"},
        {"name":"files","type":{"type":"array","items":"string"}},
        {"name":"log_size","type":"long"},
        {"name":"memory_size","type":"long"},
        {"name":"build_id","type":"long"},
        {"name":"json_key_stats_data_format","type":"long"}
      ]}}
    ]}}},
    {"name":"start_position","type":{"type":"record","name":"AvroMsgPosition","fields":[
      {"name":"channel_name","type":"string"},
      {"name":"msg_id","type":"bytes"},
      {"name":"msg_group","type":"string"},
      {"name":"timestamp","type":"long"}
    ]}},
    {"name":"dml_position","type":"AvroMsgPosition"},
    {"name":"storage_version","type":"long"},
    {"name":"is_sorted","type":"boolean"}
  ]
}`
